# permissions for end users to view scheduledscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scheduledscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scheduscaler
    app.kubernetes.io/part-of: scheduscaler
    app.kubernetes.io/managed-by: kustomize
  name: scheduledscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.vincentdeborger.be
  resources:
  - scheduledscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.vincentdeborger.be
  resources:
  - scheduledscalers/status
  verbs:
  - get
